type Group {
	id: ID!
	name: String!
	description: String
	owner: User
	notes: [Note]!
}

input NewGroupInput {
	name: String!
	description: String
	owner: ID!
}

input NewGroupUpdateInput {
	id: ID!
	name: String
	description: String
}

extend type Query {
	getGroups: [Group]!
	getGroup(groupId: ID!): Group!
}

extend type Mutation {
	newGroup(input: NewGroupInput!): Group!
	updateGroup(input: NewGroupUpdateInput!): Group!
}
