type Group {
	id: ID!
	name: String!
	description: String
	owner: User
	notes: [String]!
}

input NewGroupInput {
	name: String!
	description: String
	owner: ID!
}

extend type Query {
	getGroups: [Group]!
	getGroup(groupId: ID!): Group!
}

extend type Mutation {
	newGroup(input: NewGroupInput!): Group!
}
