type Note {
	id: ID!
	content: String!
	group: Group!
}

input NoteInput {
	id: ID!
	group: ID!
}

input NewNoteInput {
	content: String!
	group: ID!
}

input NoteUpdateInput {
	id: ID!
	content: String
	group: ID!
}

extend type Query {
	getNote(input: NoteInput!): Note!
	getNotes(group: ID!): [Note]!
}

extend type Mutation {
	newNote(input: NewNoteInput!): Note!
	updateNote(input: NoteUpdateInput!): Note!
	deleteNote(input: NoteInput!): Note!
}
